databases:
  - name: boutbuddy
    databaseName: boutbuddy
    user: boutbuddy

services:
  - type: web
    name: boutbuddy
    runtime: ruby #or env instead of runtime
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boutbuddy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
