databases:
  - name: bout-buddy
    databaseName: bout-buddy
    user: bout-buddy

services:
  - type: web
    name: bout-buddy
    runtime: ruby #or env instead of runtime
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bout-buddy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
