default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_postgres_username
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
  host: localhost
development:
  <<: *default
  database: your_application_development

test:
  <<: *default
  database: your_application_test

production:
  <<: *default
  database: your_application_production
  username: your_production_postgres_username
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>
