default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bout_buddy_development

test:
  <<: *default
  database: bout_buddy_test

production:
  <<: *default
  database: bout_buddy_production
  username: bout_buddy_board
  password: <%= ENV["BOUT_BUDDY_DATABASE_PASSWORD"] %>
